@startuml
package presentation {
  class Main
  class LinterOutputText
}

package domain {
  class LinterHandler {
    -project: ASMProject
    +runLinterAnalysis(): LinterResult
  }

  class ConvertToASM {
    -projectLocation: String
    +toASMProject(): ASMProject
    +loadClassesFromPath(path: String): List<ClassNode>
    +findAndLoadClassFiles(directory: File, classNodes: List<ClassNode>): void
    +loadClassFile(classFile: File): ClassNode
  }

  interface LintCheck {
    +name(): String
    +run(project: ASMProject): CheckResult
  }

  interface Cursory
  interface Principle
  abstract class Pattern

  Cursory ..|> LintCheck
  Principle ..|> LintCheck
  Pattern ..|> LintCheck

  class equalsChecker
  class PascalClassName
  class CamelCaseChecker
  class openClosedPrinciple

  equalsChecker --|> Cursory
  PascalClassName --|> Cursory
  CamelCaseChecker --|> Cursory
  openClosedPrinciple --|> Principle

  class TemplatePattern
  class StrategyPattern
  class DecoratorPattern
  class AdapterPattern
  class singleResponsibilityPrinciple
  class MethodTooLongPattern

  TemplatePattern --|> Pattern
  StrategyPattern --|> Pattern
  DecoratorPattern --|> Pattern
  AdapterPattern --|> Pattern
  singleResponsibilityPrinciple --|> Pattern
  MethodTooLongPattern --|> Pattern

  class Violation
  class CheckResult
  class LinterResult
}

package data {
  class ASMProject
  class ASMClass
  class ASMMethod
  class Instruction
  class StackValuePair
}

ASMProject -r-> "*" ASMClass
ASMClass -d-> "*" ASMMethod
ASMMethod -l-> "*" Instruction
Instruction ..> StackValuePair

Main --> ConvertToASM
Main --> LinterHandler
Main --> LinterOutputText

LinterHandler --> ASMProject
LinterHandler --> "*" LintCheck
LinterHandler ..> LinterResult

CheckResult --> "*" Violation
LinterResult --> "*" CheckResult

LinterOutputText ..> LinterResult

@enduml
